// src/app/master-view2/master-view2.tsx
import { IgrAvatar, IgrAvatarModule, IgrExpansionPanel, IgrExpansionPanelModule, IgrList, IgrListItem, IgrListModule } from '@infragistics/igniteui-react';
import styles from './master-view2.module.css';
import createClassTransformer from '../style-utils';

IgrAvatarModule.register();
IgrExpansionPanelModule.register();
IgrListModule.register();

export default function MasterView2() {
  const classes = createClassTransformer(styles);
  const uuid = () => crypto.randomUUID();

  return (
    <>
      <div className={classes("row-layout master-view-2-container")}>
        <IgrExpansionPanel className={classes("expansion-panel")}>
          <p className={classes("typography__body-2 text")} key={uuid()}>
            <span>Body 2</span>
          </p>
          <p className={classes("typography__body-2 text")} key={uuid()}>
            <span>Body 2</span>
          </p>
          <p className={classes("typography__body-2 text")} key={uuid()}>
            <span>Body 2</span>
          </p>
          <span slot="title" key={uuid()}>Title goes here...</span>
          <span slot="subtitle" key={uuid()}>Subtitle goes here...</span>
        </IgrExpansionPanel>
        <span className={classes("banner")}>Banner not yet available in React</span>
        <IgrExpansionPanel className={classes("expansion-panel_1")}>
          <p className={classes("typography__body-2 text")} key={uuid()}>
            <span>Body 2</span>
          </p>
          <p className={classes("typography__body-2 text")} key={uuid()}>
            <span>adsfadsghdgfhdgfj</span>
          </p>
          <span slot="title" key={uuid()}>Title goes here...</span>
          <span slot="subtitle" key={uuid()}>Subtitle goes here...</span>
        </IgrExpansionPanel>
        <div className={classes("row-layout group")}>
          <IgrExpansionPanel className={classes("expansion-panel_2")}>
            <p className={classes("typography__body-2 text")} key={uuid()}>
              <span>Body 2</span>
            </p>
            <p className={classes("typography__body-2 text")} key={uuid()}>
              <span>Body 2</span>
            </p>
            <p className={classes("typography__body-2 text")} key={uuid()}>
              <span>Body 2</span>
            </p>
            <span slot="title" key={uuid()}>Title goes here...</span>
            <span slot="subtitle" key={uuid()}>Subtitle goes here...</span>
          </IgrExpansionPanel>
        </div>
        <p className={classes("typography__body-2 text")}>
          <span>dfasgdasgfhfhdfshjjgj</span>
        </p>
        <p className={classes("typography__body-2 text")}>
          <span>dafdasgdaghhh</span>
        </p>
        <IgrAvatar shape="circle">
          <span className={classes("material-icons")} key={uuid()}>
            <span key={uuid()}>people</span>
          </span>
        </IgrAvatar>
        <IgrList className={classes("list")}>
          <IgrListItem key={uuid()}>
            <div slot="start" key={uuid()}>
              <IgrAvatar shape="circle" className={classes("avatar")} key={uuid()}>
                <span className={classes("material-icons")} key={uuid()}>
                  <span key={uuid()}>person</span>
                </span>
              </IgrAvatar>
            </div>
            <div slot="title" key={uuid()}>Title goes here</div>
            <div slot="subtitle" key={uuid()}>Subtitle...</div>
            <span slot="end" className={classes("material-icons icon")} key={uuid()}>
              <span key={uuid()}>star</span>
            </span>
          </IgrListItem>
        </IgrList>
      </div>
    </>
  );
}

// src/app/master-view2/master-view2.component.ts
import { Component } from '@angular/core';
import { IGX_BANNER_DIRECTIVES, IGX_EXPANSION_PANEL_DIRECTIVES, IGX_LIST_DIRECTIVES, IgxAvatarComponent, IgxButtonDirective, IgxIconComponent, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective } from '@infragistics/igniteui-angular';

@Component({
  selector: 'app-master-view2',
  standalone: true,
  imports: [IGX_BANNER_DIRECTIVES, IGX_EXPANSION_PANEL_DIRECTIVES, IGX_LIST_DIRECTIVES, IgxAvatarComponent, IgxButtonDirective, IgxIconComponent, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective],
  templateUrl: './master-view2.component.html',
  styleUrls: ['./master-view2.component.scss']
})
export class MasterView2Component {
}

<igx-expansion-panel class="expansion-panel">
  <igx-expansion-panel-body>
    <p class="ig-typography__body-2 text">
      Body 2
    </p>
    <p class="ig-typography__body-2 text">
      Body 2
    </p>
    <p class="ig-typography__body-2 text">
      Body 2
    </p>
  </igx-expansion-panel-body>
  <igx-expansion-panel-header>
    <igx-expansion-panel-title>Title goes here...</igx-expansion-panel-title>
    <igx-expansion-panel-description>Subtitle goes here...</igx-expansion-panel-description>
  </igx-expansion-panel-header>
</igx-expansion-panel>
<igx-banner class="banner">
  <p>
    Banner message
  </p>
  <igx-banner-actions>
    <button igxButton="flat" type="button" igxRipple class="button">
      Button
    </button>
  </igx-banner-actions>
  <igx-icon class="icon">
    mail
  </igx-icon>
</igx-banner>
<igx-expansion-panel class="expansion-panel_1">
  <igx-expansion-panel-body>
    <p class="ig-typography__body-2 text">
      Body 2
    </p>
    <p class="ig-typography__body-2 text">
      adsfadsghdgfhdgfj
    </p>
  </igx-expansion-panel-body>
  <igx-expansion-panel-header>
    <igx-expansion-panel-title>Title goes here...</igx-expansion-panel-title>
    <igx-expansion-panel-description>Subtitle goes here...</igx-expansion-panel-description>
  </igx-expansion-panel-header>
</igx-expansion-panel>
<div class="row-layout group">
  <igx-expansion-panel class="expansion-panel_2">
    <igx-expansion-panel-body>
      <p class="ig-typography__body-2 text">
        Body 2
      </p>
      <p class="ig-typography__body-2 text">
        Body 2
      </p>
      <p class="ig-typography__body-2 text">
        Body 2
      </p>
    </igx-expansion-panel-body>
    <igx-expansion-panel-header>
      <igx-expansion-panel-title>Title goes here...</igx-expansion-panel-title>
      <igx-expansion-panel-description>Subtitle goes here...</igx-expansion-panel-description>
    </igx-expansion-panel-header>
  </igx-expansion-panel>
</div>
<p class="ig-typography__body-2 text">
  dfasgdasgfhfhdfshjjgj
</p>
<p class="ig-typography__body-2 text">
  dafdasgdaghhh
</p>
<igx-avatar shape="circle">
  <igx-icon>
    people
  </igx-icon>
</igx-avatar>
<igx-list class="list">
  <igx-list-item>
    <span igxListThumbnail>
      <igx-avatar shape="circle" class="avatar">
        <igx-icon>
          person
        </igx-icon>
      </igx-avatar>
    </span>
    <span igxListLineTitle>Title goes here</span>
    <span igxListLineSubTitle>Subtitle...</span>
    <span igxListAction>
      <igx-icon class="icon">
        star
      </igx-icon>
    </span>
  </igx-list-item>
</igx-list>
