// src/app/master-view1/master-view1.component.ts
import { Component } from '@angular/core';
import { IGX_BANNER_DIRECTIVES, IGX_EXPANSION_PANEL_DIRECTIVES, IGX_STEPPER_DIRECTIVES, IgxButtonDirective, IgxIconComponent, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective } from '@infragistics/igniteui-angular';

@Component({
  selector: 'app-master-view1',
  standalone: true,
  imports: [IGX_BANNER_DIRECTIVES, IGX_EXPANSION_PANEL_DIRECTIVES, IGX_STEPPER_DIRECTIVES, IgxButtonDirective, IgxIconComponent, IgxOverlayOutletDirective, IgxRippleDirective, IgxToggleActionDirective, IgxToggleDirective],
  templateUrl: './master-view1.component.html',
  styleUrls: ['./master-view1.component.scss']
})
export class MasterView1Component {
}

<igx-stepper titlePosition="bottom" #stepper class="stepper">
  <igx-step [isValid]="false">
    <div igxStepContent class="column-layout step-content">
      <p class="text">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur soluta nulla asperiores, officia ullam recusandae voluptatem omnis perferendis vitae non magni magnam praesentium placeat nemo quas repudiandae. Nisi, quo ex!
      </p>
      <div class="row-layout group">
        <button igxButton="contained" type="button" igxRipple (click)="stepper.next()" class="button">
          Next
        </button>
      </div>
    </div>
    <p igxStepTitle>Address</p>
  </igx-step>
  <igx-step [isValid]="false">
    <div igxStepContent class="column-layout step-content">
      <p class="text">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur soluta nulla asperiores, officia ullam recusandae voluptatem omnis perferendis vitae non magni magnam praesentium placeat nemo quas repudiandae. Nisi, quo ex!
      </p>
      <div class="row-layout group">
        <button igxButton="contained" type="button" igxRipple (click)="stepper.prev()" class="button">
          Prev
        </button>
        <button igxButton="contained" type="button" igxRipple (click)="stepper.next()" class="button">
          Next
        </button>
      </div>
    </div>
    <p igxStepTitle>Item</p>
  </igx-step>
  <igx-step [optional]="true">
    <div igxStepContent class="column-layout step-content">
      <p class="text">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur soluta nulla asperiores, officia ullam recusandae voluptatem omnis perferendis vitae non magni magnam praesentium placeat nemo quas repudiandae. Nisi, quo ex!
      </p>
      <igx-expansion-panel class="expansion-panel">
        <igx-expansion-panel-body>
          <p class="ig-typography__body-2 text">
            Body 2
          </p>
          <igx-banner class="banner">
            <p>
              Banner message
            </p>
            <igx-banner-actions>
              <button igxButton="flat" type="button" igxRipple class="button_1">
                Button
              </button>
            </igx-banner-actions>
            <igx-icon class="icon">
              mail
            </igx-icon>
          </igx-banner>
        </igx-expansion-panel-body>
        <igx-expansion-panel-header>
          <igx-expansion-panel-title>Title goes here...</igx-expansion-panel-title>
          <igx-expansion-panel-description>Subtitle goes here...</igx-expansion-panel-description>
        </igx-expansion-panel-header>
      </igx-expansion-panel>
      <div class="row-layout group">
        <button igxButton="contained" type="button" igxRipple (click)="stepper.prev()" class="button">
          Prev
        </button>
        <button igxButton="contained" type="button" igxRipple (click)="stepper.reset()" class="button">
          Reset
        </button>
      </div>
    </div>
    <p igxStepTitle>Wrap</p>
    <p igxStepSubTitle>(Optional)</p>
  </igx-step>
</igx-stepper>

// src/app/master-view1/master-view1.tsx
import { IgrButton, IgrButtonModule, IgrExpansionPanel, IgrExpansionPanelModule, IgrRipple, IgrRippleModule, IgrStep, IgrStepper, IgrStepperModule } from '@infragistics/igniteui-react';
import { useRef } from 'react';
import styles from './master-view1.module.css';
import createClassTransformer from '../style-utils';

IgrButtonModule.register();
IgrExpansionPanelModule.register();
IgrRippleModule.register();
IgrStepperModule.register();

export default function MasterView1() {
  const classes = createClassTransformer(styles);
  const uuid = () => crypto.randomUUID();
  const stepper = useRef<IgrStepper>(null);

  return (
    <>
      <div className={classes("row-layout master-view-1-container")}>
        <IgrStepper titlePosition="bottom" ref={stepper} className={classes("stepper")}>
          <IgrStep invalid="true" key={uuid()}>
            <div className={classes("column-layout step-content")} key={uuid()}>
              <p className={classes("typography__body-1 text")} key={uuid()}>
                <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur soluta nulla asperiores, officia ullam recusandae voluptatem omnis perferendis vitae non magni magnam praesentium placeat nemo quas repudiandae. Nisi, quo ex!</span>
              </p>
              <div className={classes("row-layout group")} key={uuid()}>
                <IgrButton type="button" clicked={() => stepper?.current?.next()} className={classes("button")}>
                  <span key={uuid()}>Next</span>
                  <IgrRipple key={uuid()}></IgrRipple>
                </IgrButton>
              </div>
            </div>
            <p slot="title" key={uuid()}>Address</p>
          </IgrStep>
          <IgrStep invalid="true" key={uuid()}>
            <div className={classes("column-layout step-content")} key={uuid()}>
              <p className={classes("typography__body-1 text")} key={uuid()}>
                <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur soluta nulla asperiores, officia ullam recusandae voluptatem omnis perferendis vitae non magni magnam praesentium placeat nemo quas repudiandae. Nisi, quo ex!</span>
              </p>
              <div className={classes("row-layout group")} key={uuid()}>
                <IgrButton type="button" clicked={() => stepper?.current?.prev()} className={classes("button")}>
                  <span key={uuid()}>Prev</span>
                  <IgrRipple key={uuid()}></IgrRipple>
                </IgrButton>
                <IgrButton type="button" clicked={() => stepper?.current?.next()} className={classes("button")}>
                  <span key={uuid()}>Next</span>
                  <IgrRipple key={uuid()}></IgrRipple>
                </IgrButton>
              </div>
            </div>
            <p slot="title" key={uuid()}>Item</p>
          </IgrStep>
          <IgrStep optional="true" key={uuid()}>
            <div className={classes("column-layout step-content")} key={uuid()}>
              <p className={classes("typography__body-1 text")} key={uuid()}>
                <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur soluta nulla asperiores, officia ullam recusandae voluptatem omnis perferendis vitae non magni magnam praesentium placeat nemo quas repudiandae. Nisi, quo ex!</span>
              </p>
              <IgrExpansionPanel className={classes("expansion-panel")} key={uuid()}>
                <p className={classes("typography__body-2 text")} key={uuid()}>
                  <span>Body 2</span>
                </p>
                <span className={classes("banner")} key={uuid()}>Banner not yet available in React</span>
                <span slot="title" key={uuid()}>Title goes here...</span>
                <span slot="subtitle" key={uuid()}>Subtitle goes here...</span>
              </IgrExpansionPanel>
              <div className={classes("row-layout group")} key={uuid()}>
                <IgrButton type="button" clicked={() => stepper?.current?.prev()} className={classes("button")}>
                  <span key={uuid()}>Prev</span>
                  <IgrRipple key={uuid()}></IgrRipple>
                </IgrButton>
                <IgrButton type="button" clicked={() => stepper?.current?.reset()} className={classes("button")}>
                  <span key={uuid()}>Reset</span>
                  <IgrRipple key={uuid()}></IgrRipple>
                </IgrButton>
              </div>
            </div>
            <p slot="title" key={uuid()}>Wrap</p>
            <p slot="subtitle" key={uuid()}>(Optional)</p>
          </IgrStep>
        </IgrStepper>
      </div>
    </>
  );
}
